instrumentation:
  default-excludes: false
  excludes: ["**/node_modules/!(src)/**", "**/test/**"]
  compact: false
  save-baseline: true
reporting:
  dir: ./coverage
  print: summary
  reports:
    - lcov
